#!/bin/bash -v
export WORKSPACE=/apdcephfs/share_887471/interns/v_willwhua/code/ie_e2e
#export WORKSPACE=/apdcephfs/private_v_fisherwyu/code/code/ie_e2e
#sh ${WORKSPACE}/taiji/multi_train.sh
#sh ${WORKSPACE}/taiji/single_test.sh
#sh ${WORKSPACE}/taiji/train_finetune.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_0.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_1.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_1_0.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_1_1.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_1_2.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_2.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_2_0.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_2_0_0.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_2_1.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_2_1_0.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_2_2.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_2_2_0.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_2_3.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_3.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_4.sh
#sh ${WORKSPACE}/taiji/multi_train_sroie_5.sh
#sh ${WORKSPACE}/taiji/multi_train_nfv3_0.sh
#sh ${WORKSPACE}/taiji/multi_train_nfv3_1.sh
#sh ${WORKSPACE}/taiji/multi_train_nfv3_2.sh
#sh ${WORKSPACE}/taiji/pretrian_0.sh
#sh ${WORKSPACE}/taiji/pretrian_1.sh
#sh ${WORKSPACE}/taiji/multi_train_nar_sroie_0.sh
#sh ${WORKSPACE}/taiji/multi_train_nar_sroie_1.sh